version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
      - npm run build
    run-as: root
#  pre_build:
#    commands:
#      - npm install
##      - npm i --arch=arm64 --target_platform=linux --production
#  build:
#    commands:
#      - npm run build
artifacts:
#  type: zip
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*'
