version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  files:
    - '**/*'
#cache:
#  paths:
#    - 'node_modules/**/*'
