version: 0.2

phases:
  pre_build:
    commands:
#      - npm install
      - npm i --target_arch=arm --target_platform=linux --arch=arm --production
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*'
