version: "3.7"
services:
  pm2:
    container_name: pm2
    restart: always
    build:
      context: ../
      dockerfile: ./docker-compose/pm2/Dockerfile
    volumes:
      - ../:/app
    ports:
      - "${HTTP_PORT}:3000"