version: "3.7"
services:
  pm2:
    container_name: pm2
    build:
      context: ../
      dockerfile: ./docker-compose/pm2/Dockerfile
    volumes:
      - ../:/app

  web:
    container_name: web
    image: nginx:1.20.1
    volumes:
      - ../:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "${HTTP_PORT}:80"
    links:
      - pm2